interface=eth0
bind-interfaces
log-dhcp

# Proxy DHCP
dhcp-range=192.168.68.0,proxy

# MAC tagging
dhcp-host=ec:f4:bb:e5:aa:fb,set:nic1
dhcp-host=00:15:5d:05:71:00,set:nic2

# PXE boot selection
pxe-service=tag:nic1,X86-64_EFI,"NIC1 Boot",ipxe-nic1.efi
pxe-service=tag:nic2,X86-64_EFI,"NIC2 Boot",ipxe-nic2.efi
pxe-service=X86-64_EFI,"Default Boot",ipxe-default.efi
